apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sonarqube-admin-rolebinding
  namespace: sonar
  labels:
    app: sonarqube
roleRef:
  apiGroup: rbac.authorization.k8s.io 
  kind: ClusterRole
  name: admin
subjects:
 - kind: ServiceAccount
   name: sonarqube
   namespace: soonarqube