---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: jenkins
  name: jenkins-pv
  labels: 
     app: jenkins
     purpose: devops
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: "/home/ubuntu/data/jenkins_data"
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  capacity:
    storage: 5Gi
  claimRef:
    name: jenkins-pvc
    namespace: jenkins
