---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: jenkins
  name: jenkins-pvc
  labels:
    app: jenkins
    purpose: devops
spec: 
  accessModes:
  - ReadWriteOnce
  volumeName: jenkins-pv
  volumeMode: Filesystem
  storageClassName: slow
  selector:
    matchLabels:
       app: jenkins
  resources:
    requests:
      storage: 5Gi