apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-admin-rolebinding
  namespace: jenkins
  labels:
    app: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io 
  kind: ClusterRole
  name: system:jenkins
subjects:
 - kind: ServiceAccount
   name: jenkins
   namespace: jenkins